mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/DYJetsToLL_M-10To50mumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/DYJetsToLL_M-10To50mumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/DYJetsToLL_M-50mumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/DYJetsToLL_M-50mumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/sChannelmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/sChannelmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tbarChannelmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tbarChannelmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tbarWInclusivemumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tbarWInclusivemumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tChannelmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tChannelmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tHqmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tHqmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttbarInclusivePowerhegmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttbarInclusivePowerhegmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttW2qmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttW2qmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttWlnumumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttWlnumumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttZ2l2numumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttZ2l2numumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttZ2qmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ttZ2qmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tWInclusivemumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tWInclusivemumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tWZmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tWZmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tZqmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/tZqmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/wPlusJetsmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/wPlusJetsmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WW1l1nu2qmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WW1l1nu2qmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WW2l2numumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WW2l2numumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WZ1l1nu2qmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WZ1l1nu2qmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WZ2l2qmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WZ2l2qmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WZjetsmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/WZjetsmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ZZ2l2numumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ZZ2l2numumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ZZ2l2qmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ZZ2l2qmumuinvLep_part2mvaOut.root
mv /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ZZ4lmumuinvLepmvaOut.root /scratch/data/TopPhysics/mvaDirs/skims/2016/mz5mw50/ZZ4lmumuinvLep_part2mvaOut.root
